#!/bin/bash

cd /tmp
fusermount -u fuse
rm -r fuse/
mkdir fuse
chmod 755 fuse/
# Change path
cd /home/kristian/documents/4.-semester/file_system/assignment3/sources
./lfs /tmp/fuse/ &

cd /tmp/fuse

echo "--------Test#1: Creating directories --------"
mkdir dirs
cd dirs
mkdir a b c d e
cd a
mkdir a b c d e
cd b
mkdir a b c d e
cd e
mkdir help me i am trapped 
cd trapped 
mkdir still trapped
cd trapped 
tree /tmp/fuse/
echo "-------- Sucess --------"

echo " " 
sleep 5
echo "--------Test#2: Removing all directories + sub-directories --------"

cd /tmp/fuse
rm -r dirs

tree /tmp/fuse/
echo "-------- Sucess --------"
sleep 2

echo " " 

