#!/bin/bash

echo "-------- Test#3: Testing resizing --------"
cd /tmp/fuse 
mkdir tests
cd tests
for i in {1..11}; do mkdir $i; done;
for i in {1..11}; do touch $i.txt; done;
cd 1
for i in {1..11}; do touch $i.txt; done;

tree /tmp/fuse/
sleep 2
echo "-------- Sucess --------"

echo " " 
cd /tmp/fuse 
rm -r tests
