#!/bin/bash
cd /tmp/fuse
mkdir a
cd a

echo "-------- Test#4: Testing make file --------"
touch file.txt
ls
sleep 4
echo "-------- Success  --------"
echo " " 

echo "-------- Test#5: Testing write data file --------"
echo I am a long text file or something like that > file.txt 
cat file.txt
ls -la
sleep 4
echo "-------- Success  --------"
echo  " " 

echo "-------- Test#6: Testing delete file with data --------"
rm file.txt 
ls -la 
sleep 4
echo "-------- Success  --------"
echo " " 

echo "-------- Test#7: Testing create duplicate file names  --------"
touch file.txt
echo " " 
echo "-------- file.txt created --------" 
echo i am the orginal file > file.txt
echo "Content of file.txt: $(cat file.txt)" 
echo " " 

sleep 3
echo "-------- trying to duplicate it --------" 
echo " " 
touch file.txt
ls -la
sleep 3
echo "Content of file.txt: $(cat file.txt)" 
sleep 4
echo "-------- Success: duplication not possible  --------"

echo " " 
cd /tmp/fuse/
rm -r a
