#!/bin/bash
cd /tmp/fuse

echo "Creating directories"
mkdir dirs
cd dirs
mkdir a b c d e
cd a
mkdir a b c d e
cd b
mkdir a b c d e
cd e
mkdir help me i am trapped 
cd trapped 
mkdir still trapped
cd trapped 
tree /tmp/fuse/
echo "-------- Sucess --------"

sleep 5
echo "-------- Removing all directories + sub-directories --------"

cd /tmp/fuse
rm -r dirs

tree /tmp/fuse/
echo "-------- Sucess --------"
sleep 2

