#!/bin/bash

echo "-------- Test#3: Testing resizing --------"
cd /tmp/fuse 
mkdir tests
cd tests
for i in {1..111}; do mkdir $i; done;
for i in {1..111}; do touch $i.txt; done;
ls
sleep 1
cd 1
for i in {1..11}; do touch $i.txt; done;
ls

tree /tmp/fuse/
sleep 1
echo "-------- Sucess --------"

cd /tmp/fuse 
rm -r tests
