#!/bin/bash
cd /tmp/fuse
echo "-------- Test#4: Testing make file --------"
mkdir a
touch a
tree

sleep 2

rm -r /tmp/fuse/*
touch a b c d e
ls -la

sleep 2
echo "-------- Test#5: Testing write file --------"
