#!/bin/bash
echo "-------- Test8: Creating dir, which name is already a file --------"
cd /tmp/fuse

mkdir test 
cd test

touch a
mkdir a
ls 
echo "-------- Sucess --------"
sleep 2
echo "-------- Test9: Creating file, which name is already a dir --------"
mkdir b
touch b
echo "-------- Sucess --------"
sleep 2
